## 판다스 데이터 처리

### 데이터 정제

- 결측값(치)와 이상치를 제거하고 분석가능한 깨끗한 데이터로 수정하는 작업
    - 결측값 : NULL, None, Nan 등 입력되지 않은 필요한 데이터. 나이 컬럼에 값 없음 
    - 이상치 : 컬럼 도메인에 알맞지 않은 데이터. 점수 999점  
    - 중복값 : 중복된 데이터. 같은 학생이 두 번 등록
    - 타입오류 : 일치하지 않는 데이터 타입으로 입력된 값. 점수에 문자열로 저장. '구십구점'
    - 불필요한 공백 : 필요없는 스페이스키 입력 '  홍길동  '
    - 도메인 오류 : 표현방식 일치. 'M', 'Male', '남자', '남성'...
- 위 문제들을 해결하지 않으면 통계(계산)를 낼 수 없음

### 데이터 전처리

- 데이터 정제를 하는 과정, 분석 프로젝트의 40~50% 차지 
- AI 시대에서는 정제 과정이 많이 축소될 것으로 예상
- 사람의 검수 반드시 필요. 시간 대부분 여기에서 소요

### 학생 성적 데이터 정제

In [2]:
import numpy as np 
import pandas as pd

In [3]:
data = {
    "name": [
        "홍길동", "김철수", "이영희", "박민수", "홍길동",
        " 최지훈 ", "김민지", "이수진", "박지성", "정우성",
        "강동원", "송혜교", "김태희", "전지현", "손흥민",
        "황희찬", "김연아", "박보검", "아이유", "유재석",
        "강호동", "신동엽", "이효리", "김종국", "하정우",
        " 이정재", "정우성 ", "김혜수", None, "최민식",
        "김지원", "박서준", "한소희", "남주혁", "수지",
        "공유", "김고은", "현빈", "손예진", "조정석",
        "김다미", "최우식", "이병헌", "한지민", "마동석",
        "김우빈", "신민아", "이성민", "임시완", "윤아 "
    ],

    "age": [
        20, 21, np.nan, 23, 20,
        24, 22, 21, 25, 26,
        27, 22, 21, 23, 24,
        25, np.nan, 22, 21, 30,
        31, 29, 28, 27, 26,
        150, 26, 25, 24, -5,
        23, 22, 21, 25, 24,
        28, 23, 29, 27, 26,
        np.nan, 24, 200, 22, 30,
        27, 26, 25, 23, 24
    ],

    "gender": [
        "남", "남자", "여", "남", "남",
        "M", "여자", "여", "남성", "남",
        "남", "F", "여", "여성", "남",
        "남자", "F", "남", "여", "남",
        "M", "남", "여자", "남성", "남",
        "남", "남", "여", None, "남자",
        "여", "남", "F", "남자", "여성",
        "M", "여", "남성", "여자", "남",
        "F", "남", "남자", "여", "남성",
        "M", "여성", "남", "남자", "F"
    ],

    "score": [
        85, 90, 999, 70, 85,
        "88", 92, 76, 81, 95,
        100, np.nan, 89, 91, 84,
        78, 96, 73, 87, 65,
        68, 77, 93, 82, 79,
        -10, 105, "90", None, 88,
        91, 83, 77, 94, 86,
        72, 89, 98, 92, 81,
        np.nan, 75, 150, 88, 69,
        "95", 84, 79, 90, 87
    ],

    "email": [
        "hong@example.com",
        "kim@example.com",
        None,
        "park@example.com",
        "hong@example.com",
        "choi@example.com",
        "minji@example.com",
        "sujin@example.com",
        "jisung@example.com",
        "woosung@example.com",
        "dongwon@example.com",
        "hyekyo@example.com",
        "taehee@example.com",
        "jihyun@example.com",
        "heungmin@example.com",
        "heechan@example.com",
        None,
        "bogum@example.com",
        "iu@example.com",
        "jaesuk@example.com",
        "hodong@example.com",
        "dongyeop@example.com",
        "hyori@example.com",
        "jongkook@example.com",
        "jungwoo@example.com",
        "jungjae@example",
        "woosung@example.com",
        "hysoo@example.com",
        "",
        "minsig @example.com",
        "jiwon@example.com",
        "seojun@example.com",
        "sohee@example.com",
        "joohyuk@example.com",
        "suzy@example.com",
        "gongyoo@example.com",
        "goeun@example.com",
        "hyunbin@example.com",
        "yejin@example.com",
        "jungsuk@example.com",
        "dami@example.com",
        "woosik@example.com",
        "byunghun@example.com",
        "jimin@example.com",
        "dongseok@example.com",
        "woobin@example.com",
        "minah@example.com",
        "sungmin@example.com",
        "siwan@example.com",
        "yoona@example"
    ]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

     name    age gender score                 email
0     홍길동   20.0      남    85      hong@example.com
1     김철수   21.0     남자    90       kim@example.com
2     이영희    NaN      여   999                   NaN
3     박민수   23.0      남    70      park@example.com
4     홍길동   20.0      남    85      hong@example.com
5    최지훈    24.0      M    88      choi@example.com
6     김민지   22.0     여자    92     minji@example.com
7     이수진   21.0      여    76     sujin@example.com
8     박지성   25.0     남성    81    jisung@example.com
9     정우성   26.0      남    95   woosung@example.com
10    강동원   27.0      남   100   dongwon@example.com
11    송혜교   22.0      F   NaN    hyekyo@example.com
12    김태희   21.0      여    89    taehee@example.com
13    전지현   23.0     여성    91    jihyun@example.com
14    손흥민   24.0      남    84  heungmin@example.com
15    황희찬   25.0     남자    78   heechan@example.com
16    김연아    NaN      F    96                   NaN
17    박보검   22.0      남    73     bogum@example.com
18    아이유   21.0      여    87        iu@example.com
19    유재석   30.0      남    65    jaesuk@example.com
20    강호동   31.0      M    68    hodong@example.com
21    신동엽   29.0      남    77  dongyeop@example.com
22    이효리   28.0     여자    93     hyori@example.com
23    김종국   27.0     남성    82  jongkook@example.com
24    하정우   26.0      남    79   jungwoo@example.com
25    이정재  150.0      남   -10       jungjae@example
26   정우성    26.0      남   105   woosung@example.com
27    김혜수   25.0      여    90     hysoo@example.com
28    NaN   24.0    NaN  None
29    최민식   -5.0     남자    88   minsig @example.com
30    김지원   23.0      여    91     jiwon@example.com
31    박서준   22.0      남    83    seojun@example.com
32    한소희   21.0      F    77     sohee@example.com
33    남주혁   25.0     남자    94   joohyuk@example.com
34     수지   24.0     여성    86      suzy@example.com
35     공유   28.0      M    72   gongyoo@example.com
36    김고은   23.0      여    89     goeun@example.com
37     현빈   29.0     남성    98   hyunbin@example.com
38    손예진   27.0     여자    92     yejin@example.com
39    조정석   26.0      남    81   jungsuk@example.com
40    김다미    NaN      F   NaN      dami@example.com
41    최우식   24.0      남    75    woosik@example.com
42    이병헌  200.0     남자   150  byunghun@example.com
43    한지민   22.0      여    88     jimin@example.com
44    마동석   30.0     남성    69  dongseok@example.com
45    김우빈   27.0      M    95    woobin@example.com
46    신민아   26.0     여성    84     minah@example.com
47    이성민   25.0      남    79   sungmin@example.com
48    임시완   23.0     남자    90     siwan@example.com
49    윤아    24.0      F    87         yoona@example

- 중복된 데이터 존재
- age에 결측치 존재 
- email에 결측치 존재 
- score에 이상치 존재 
- gender 표현방식 불일치 
- name에 공백

#### 데이터 구조 확인

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    49 non-null     str
 1   age     47 non-null     float64
 2   gender  49 non-null     str
 3   score   47 non-null     object
 4   email   48 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.1+ KB

In [9]:
df.head()

  name   age gender score             email
0  홍길동  20.0      남    85  hong@example.com
1  김철수  21.0     남자    90   kim@example.com
2  이영희   NaN      여   999               NaN
3  박민수  23.0      남    70  park@example.com
4  홍길동  20.0      남    85  hong@example.com

In [10]:
df.tail()

   name   age gender score                email
45  김우빈  27.0      M    95   woobin@example.com
46  신민아  26.0     여성    84    minah@example.com
47  이성민  25.0      남    79  sungmin@example.com
48  임시완  23.0     남자    90    siwan@example.com
49  윤아   24.0      F    87        yoona@example

In [11]:
df.shape

(50, 5)

#### 결측값 확인

In [16]:
# 각 컬럼별 결측치 갯수 확인
df.isna().sum()

name      1
age       3
gender    1
score     3
email     2
dtype: int64

In [20]:
df.describe()

              age
count   47.000000
mean    30.361702
std     31.676644
min     -5.000000
25%     22.000000
50%     24.000000
75%     27.000000
max    200.000000

- score 통계가 안나옴. score의 데이터타입이 숫자대신 object
- score 컬럼에 존재하는 수 이외에 값을 정제필요

In [22]:
# 결측치 확인
df.isnull() # insa() 동일

     name    age  gender  score  email
0   False  False   False  False  False
1   False  False   False  False  False
2   False   True   False  False   True
3   False  False   False  False  False
4   False  False   False  False  False
5   False  False   False  False  False
6   False  False   False  False  False
7   False  False   False  False  False
8   False  False   False  False  False
9   False  False   False  False  False
10  False  False   False  False  False
11  False  False   False   True  False
12  False  False   False  False  False
13  False  False   False  False  False
14  False  False   False  False  False
15  False  False   False  False  False
16  False   True   False  False   True
17  False  False   False  False  False
18  False  False   False  False  False
19  False  False   False  False  False
20  False  False   False  False  False
21  False  False   False  False  False
22  False  False   False  False  False
23  False  False   False  False  False
24  False  False   False  False  False
25  False  False   False  False  False
26  False  False   False  False  False
27  False  False   False  False  False
28   True  False    True   True  False
29  False  False   False  False  False
30  False  False   False  False  False
31  False  False   False  False  False
32  False  False   False  False  False
33  False  False   False  False  False
34  False  False   False  False  False
35  False  False   False  False  False
36  False  False   False  False  False
37  False  False   False  False  False
38  False  False   False  False  False
39  False  False   False  False  False
40  False   True   False   True  False
41  False  False   False  False  False
42  False  False   False  False  False
43  False  False   False  False  False
44  False  False   False  False  False
45  False  False   False  False  False
46  False  False   False  False  False
47  False  False   False  False  False
48  False  False   False  False  False
49  False  False   False  False  False

In [24]:
df.isnull().sum()

name      1
age       3
gender    1
score     3
email     2
dtype: int64

- ""빈 문자열은 결측치에 합산되지 않음!

#### 빈 문자열 처리

"" 빈 공백 문자열을 NaN으로 변경

In [25]:
# 이메일이 공백인 데이터를 NaN으로 변경
df['email'] = df['email'].replace("", np.nan)

In [26]:
df.isnull().sum()

name      1
age       3
gender    1
score     3
email     3
dtype: int64

In [27]:
df

     name    age gender score                 email
0     홍길동   20.0      남    85      hong@example.com
1     김철수   21.0     남자    90       kim@example.com
2     이영희    NaN      여   999                   NaN
3     박민수   23.0      남    70      park@example.com
4     홍길동   20.0      남    85      hong@example.com
5    최지훈    24.0      M    88      choi@example.com
6     김민지   22.0     여자    92     minji@example.com
7     이수진   21.0      여    76     sujin@example.com
8     박지성   25.0     남성    81    jisung@example.com
9     정우성   26.0      남    95   woosung@example.com
10    강동원   27.0      남   100   dongwon@example.com
11    송혜교   22.0      F   NaN    hyekyo@example.com
12    김태희   21.0      여    89    taehee@example.com
13    전지현   23.0     여성    91    jihyun@example.com
14    손흥민   24.0      남    84  heungmin@example.com
15    황희찬   25.0     남자    78   heechan@example.com
16    김연아    NaN      F    96                   NaN
17    박보검   22.0      남    73     bogum@example.com
18    아이유   21.0      여    87        iu@example.com
19    유재석   30.0      남    65    jaesuk@example.com
20    강호동   31.0      M    68    hodong@example.com
21    신동엽   29.0      남    77  dongyeop@example.com
22    이효리   28.0     여자    93     hyori@example.com
23    김종국   27.0     남성    82  jongkook@example.com
24    하정우   26.0      남    79   jungwoo@example.com
25    이정재  150.0      남   -10       jungjae@example
26   정우성    26.0      남   105   woosung@example.com
27    김혜수   25.0      여    90     hysoo@example.com
28    NaN   24.0    NaN  None                   NaN
29    최민식   -5.0     남자    88   minsig @example.com
30    김지원   23.0      여    91     jiwon@example.com
31    박서준   22.0      남    83    seojun@example.com
32    한소희   21.0      F    77     sohee@example.com
33    남주혁   25.0     남자    94   joohyuk@example.com
34     수지   24.0     여성    86      suzy@example.com
35     공유   28.0      M    72   gongyoo@example.com
36    김고은   23.0      여    89     goeun@example.com
37     현빈   29.0     남성    98   hyunbin@example.com
38    손예진   27.0     여자    92     yejin@example.com
39    조정석   26.0      남    81   jungsuk@example.com
40    김다미    NaN      F   NaN      dami@example.com
41    최우식   24.0      남    75    woosik@example.com
42    이병헌  200.0     남자   150  byunghun@example.com
43    한지민   22.0      여    88     jimin@example.com
44    마동석   30.0     남성    69  dongseok@example.com
45    김우빈   27.0      M    95    woobin@example.com
46    신민아   26.0     여성    84     minah@example.com
47    이성민   25.0      남    79   sungmin@example.com
48    임시완   23.0     남자    90     siwan@example.com
49    윤아    24.0      F    87         yoona@example

### 결측치 행 확인

In [29]:
df.isnull()

     name    age  gender  score  email
0   False  False   False  False  False
1   False  False   False  False  False
2   False   True   False  False   True
3   False  False   False  False  False
4   False  False   False  False  False
5   False  False   False  False  False
6   False  False   False  False  False
7   False  False   False  False  False
8   False  False   False  False  False
9   False  False   False  False  False
10  False  False   False  False  False
11  False  False   False   True  False
12  False  False   False  False  False
13  False  False   False  False  False
14  False  False   False  False  False
15  False  False   False  False  False
16  False   True   False  False   True
17  False  False   False  False  False
18  False  False   False  False  False
19  False  False   False  False  False
20  False  False   False  False  False
21  False  False   False  False  False
22  False  False   False  False  False
23  False  False   False  False  False
24  False  False   False  False  False
25  False  False   False  False  False
26  False  False   False  False  False
27  False  False   False  False  False
28   True  False    True   True   True
29  False  False   False  False  False
30  False  False   False  False  False
31  False  False   False  False  False
32  False  False   False  False  False
33  False  False   False  False  False
34  False  False   False  False  False
35  False  False   False  False  False
36  False  False   False  False  False
37  False  False   False  False  False
38  False  False   False  False  False
39  False  False   False  False  False
40  False   True   False   True  False
41  False  False   False  False  False
42  False  False   False  False  False
43  False  False   False  False  False
44  False  False   False  False  False
45  False  False   False  False  False
46  False  False   False  False  False
47  False  False   False  False  False
48  False  False   False  False  False
49  False  False   False  False  False

In [ ]:
# 이름이 결측치인 데이터 
df[df['name'].isnull()]

   name   age gender score email
28  NaN  24.0    NaN  None   NaN

In [32]:
# 나이가 결측치인 데이터 
df[df['age'].isnull()]

   name  age gender score             email
2   이영희  NaN      여   999               NaN
16  김연아  NaN      F    96               NaN
40  김다미  NaN      F   NaN  dami@example.com

In [33]:
# 성별이 결측치인 데이터 
df[df['gender'].isnull()]

   name   age gender score email
28  NaN  24.0    NaN  None   NaN

In [34]:
# 성적이 결측치인 데이터 
df[df['score'].isnull()]

   name   age gender score               email
11  송혜교  22.0      F   NaN  hyekyo@example.com
28  NaN  24.0    NaN  None                 NaN
40  김다미   NaN      F   NaN    dami@example.com

In [35]:
# 이메일이 결측치인 데이터 
df[df['email'].isnull()]

   name   age gender score email
2   이영희   NaN      여   999   NaN
16  김연아   NaN      F    96   NaN
28  NaN  24.0    NaN  None   NaN

#### 결측치 처리

##### 1. 행 전체를 삭제

- 결측치가 존재하는 컬럼(열)이 하나라도 있으면 무조건 행 삭제

In [40]:
df_dropna = df.dropna()

In [19]:
df_dropna

     name    age gender score                 email
0     홍길동   20.0      남    85      hong@example.com
1     김철수   21.0     남자    90       kim@example.com
3     박민수   23.0      남    70      park@example.com
4     홍길동   20.0      남    85      hong@example.com
5    최지훈    24.0      M    88      choi@example.com
6     김민지   22.0     여자    92     minji@example.com
7     이수진   21.0      여    76     sujin@example.com
8     박지성   25.0     남성    81    jisung@example.com
9     정우성   26.0      남    95   woosung@example.com
10    강동원   27.0      남   100   dongwon@example.com
12    김태희   21.0      여    89    taehee@example.com
13    전지현   23.0     여성    91    jihyun@example.com
14    손흥민   24.0      남    84  heungmin@example.com
15    황희찬   25.0     남자    78   heechan@example.com
17    박보검   22.0      남    73     bogum@example.com
18    아이유   21.0      여    87        iu@example.com
19    유재석   30.0      남    65    jaesuk@example.com
20    강호동   31.0      M    68    hodong@example.com
21    신동엽   29.0      남    77  dongyeop@example.com
22    이효리   28.0     여자    93     hyori@example.com
23    김종국   27.0     남성    82  jongkook@example.com
24    하정우   26.0      남    79   jungwoo@example.com
25    이정재  150.0      남   -10       jungjae@example
26   정우성    26.0      남   105   woosung@example.com
27    김혜수   25.0      여    90     hysoo@example.com
29    최민식   -5.0     남자    88   minsig @example.com
30    김지원   23.0      여    91     jiwon@example.com
31    박서준   22.0      남    83    seojun@example.com
32    한소희   21.0      F    77     sohee@example.com
33    남주혁   25.0     남자    94   joohyuk@example.com
34     수지   24.0     여성    86      suzy@example.com
35     공유   28.0      M    72   gongyoo@example.com
36    김고은   23.0      여    89     goeun@example.com
37     현빈   29.0     남성    98   hyunbin@example.com
38    손예진   27.0     여자    92     yejin@example.com
39    조정석   26.0      남    81   jungsuk@example.com
41    최우식   24.0      남    75    woosik@example.com
42    이병헌  200.0     남자   150  byunghun@example.com
43    한지민   22.0      여    88     jimin@example.com
44    마동석   30.0     남성    69  dongseok@example.com
45    김우빈   27.0      M    95    woobin@example.com
46    신민아   26.0     여성    84     minah@example.com
47    이성민   25.0      남    79   sungmin@example.com
48    임시완   23.0     남자    90     siwan@example.com
49    윤아    24.0      F    87         yoona@example

In [41]:
df_dropna.info()

<class 'pandas.DataFrame'>
Index: 45 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    45 non-null     str
 1   age     45 non-null     float64
 2   gender  45 non-null     str
 3   score   45 non-null     object
 4   email   45 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.1+ KB

- 결측치를 그냥 제거하면 모수가 예상보다 많이 줄어듦. 통계치에 오차가 생김
- 필터링으로 정말 삭제할 행만 삭제

##### 2. 이메일 필터링으로 행 삭제

In [37]:
# email이 결측치이면 행 제거

df_dropna_email = df.dropna(subset = ['email'])

In [39]:
df_dropna_email.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    47 non-null     str
 1   age     46 non-null     float64
 2   gender  47 non-null     str
 3   score   45 non-null     object
 4   email   47 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.2+ KB

##### 3. 평균값으로 채우기

In [43]:
df[df['age'].isnull()]

   name  age gender score             email
2   이영희  NaN      여   999               NaN
16  김연아  NaN      F    96               NaN
40  김다미  NaN      F   NaN  dami@example.com

In [44]:
df['age'].mean()

np.float64(30.361702127659573)

- 평균값으로 채우기 전 확인 결과, 나이에 이상치 발견
- 150세, -5세, 200세 ... 존재

#### 이상치 처리

##### 1. 나이 컬럼 이상치 정제

In [68]:
df['age'].describe()

count    50.00000
mean     24.64000
std       2.67841
min      20.00000
25%      23.00000
50%      25.00000
75%      26.00000
max      31.00000
Name: age, dtype: float64

In [69]:
df[(df['age'] < 11) | (df['age'] > 69)]

Empty DataFrame
Columns: [name, age, gender, score, email]
Index: []

In [52]:
# 이상치를 NaN으로 변경
df.loc[(df['age'] < 11) | (df['age'] > 69), 'age'] = np.nan